### ISSUE TITLE
Failed to load the experiment `loicbarrault/loicbarrault/translation_ll_dev/1/translation_ll_dev':

### ISSUE THREAD

**Issue by gdxie1** [loicbarrault/allies_llmt_beat#2]
beat --prefix ./beat experiments run loicbarrault/loicbarrault/translation_ll_dev/1/translation_ll_dev
When I run the above command, it gives following error. Please help to check it. Thanks
Failed to load the experiment `loicbarrault/loicbarrault/translation_ll_dev/1/translation_ll_dev':
  * toolchain `loicbarrault/translation_ll_dev/1' is not valid, because:
  * /representation: 'loops' is a required property (rule: /properties/representation/required)
Error: Error occured

**Comment by mbiesialska** [comment]
Hi @gdxie1
for [this year's WMT shared task](http://www.statmt.org/wmt21/lifelong-learning-task.html) we use the [following github repo](https://github.com/llmt-wmt/allies_llmt_beat). Can you try with this one?
Please make sure to remove `beat_allies` conda environment before proceeding with the installation steps described in this [new github repo](https://github.com/llmt-wmt/allies_llmt_beat).
Hope it helps!
